image: mcr.microsoft.com/dotnet/nightly/sdk:9.0-preview

stages:
  - build
  - test
  - sonarqube-check
  - sonarqube-vulnerability-report
  - deploy-api
  - deploy-web


variables:
  coffee_solution: "Coffee.sln" # Pfad zur Lsungsdatei deines Projekts
  test_project: "CoffeeTest/CoffeeTest.csproj" # Pfad zum Testprojekt
  MONGO_USER: $MONGO_USER
  MONGO_PASSWORD: $MONGO_PASSWORD

before_script:
  - 'dotnet restore $coffee_solution'

build:
  stage: build
  script:
    - 'dotnet build $coffee_solution'
  allow_failure: false
  only:
    - merge_requests
    - master
    - main
    - dev

test:
  stage: test
  script:
    - 'dotnet test $test_project'
  allow_failure: true
  only:
    - merge_requests
    - master
    - main
    - dev

sonarqube-check:
  stage: sonarqube-check
  image: mcr.microsoft.com/dotnet/nightly/sdk:9.0-preview
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
      - "apt-get update"
      - "apt-get install --yes --no-install-recommends openjdk-17-jre"
      - "dotnet tool install --global dotnet-sonarscanner"
      - "export PATH=\"$PATH:$HOME/.dotnet/tools\""
      - "dotnet sonarscanner begin /k:\"gereon_coffee_ba5c47bb-a0a1-4e5a-b9d6-2187da863b11\" /d:sonar.token=\"$SONAR_TOKEN\" /d:\"sonar.host.url=$SONAR_HOST_URL\" "
      - "dotnet build"
      - "dotnet sonarscanner end /d:sonar.token=\"$SONAR_TOKEN\""
  allow_failure: true
  only:
    - merge_requests
    - master
    - main
    - dev

sonarqube-vulnerability-report:
  stage: sonarqube-vulnerability-report
  script:
    - 'curl -u "${SONAR_TOKEN}:" "${SONAR_HOST_URL}/api/issues/gitlab_sast_export?projectKey=gereon_coffee_ba5c47bb-a0a1-4e5a-b9d6-2187da863b11&branch=${CI_COMMIT_BRANCH}&pullRequest=${CI_MERGE_REQUEST_IID}" -o gl-sast-sonar-report.json'
  allow_failure: true
  only:
    - merge_requests
    - master
    - main
    - dev
  artifacts:
    expire_in: 1 day
    reports:
      sast: gl-sast-sonar-report.json
  dependencies:
    - sonarqube-check

deploy-api:
  stage: deploy-api
  only:
    - master
    - main
  script:
    - cd CoffeeApi
    - docker build -t my-coffee-web .

  dependencies:
    - build
deploy-web:
  stage: deploy-web
  only:
    - master
    - main  
  script:
    - cd CoffeeWeb
    - docker build -t my-coffee-api .
  dependencies:
    - build