name: Build and Push API Container
run-name: ${{ gitea.actor }} is Building and Pushing API Container 🚀
on:
  push:
    branches:
      - main
      - 'releases/**'

jobs:
 steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker registry
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin 192.168.2.143:3000
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t 192.168.2.143:3000/gereon/nivona-web:latest .
        working-directory: CoffeeApi/  # Adjust the path to the directory containing your Dockerfile

      - name: Push Docker image
        run: |
          docker push 192.168.2.143:3000/gereon/nivona-web:latest