// <auto-generated />
using System;
using CoffeeApi.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeeApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260820221335_AddBeanHopperOverrides")]
    partial class AddBeanHopperOverrides
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("CoffeeApi.Domain.BeanHopperOverride", b =>
                {
                    b.Property<int>("SnapshotId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Counter")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("BeanHopper")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("SnapshotId", "Counter");

                    b.ToTable("BeanHopperOverrides");
                });

            modelBuilder.Entity("CoffeeApi.Domain.MachineSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeverageCounterCoffee")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeverageCounterCoffeeAndMilk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeverageCounterHotWater")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeverageCounterHotWaterCups")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeverageCounterMilk")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("InteriorIlluminationActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LocalControlActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("EQ900-DEFAULT");

                    b.Property<string>("OperationState")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RemoteControlAllowed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MachineId")
                        .HasDatabaseName("IX_MachineSnapshots_MachineId");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_MachineSnapshots_Timestamp");

                    b.ToTable("MachineSnapshots");
                });

            modelBuilder.Entity("CoffeeApi.Domain.MarkedDay", b =>
                {
                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("mass-import");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Date");

                    b.ToTable("MarkedDays");
                });

            modelBuilder.Entity("CoffeeApi.Domain.BeanHopperOverride", b =>
                {
                    b.HasOne("CoffeeApi.Domain.MachineSnapshot", null)
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
