// <auto-generated />
using System;
using CoffeeApi.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeeApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260418215802_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("CoffeeApi.Domain.MachineSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeverageCounterCoffee")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeverageCounterCoffeeAndMilk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeverageCounterHotWater")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeverageCounterHotWaterCups")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeverageCounterMilk")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("InteriorIlluminationActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LocalControlActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("EQ900-DEFAULT");

                    b.Property<string>("OperationState")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RemoteControlAllowed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MachineId")
                        .HasDatabaseName("IX_MachineSnapshots_MachineId");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_MachineSnapshots_Timestamp");

                    b.HasIndex("MachineId", "BeverageCounterCoffee", "BeverageCounterCoffeeAndMilk", "BeverageCounterMilk")
                        .HasDatabaseName("IX_MachineSnapshots_Idempotency");

                    b.ToTable("MachineSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
